### ISSUE TITLE
Error occurs if -num-messages exceeds 220

### ISSUE THREAD

**Issue by choclaudio** [inovex/mqtt-stresser#13]
Any number of clients with  -num-messages exceeding 220 will result in a crash.
ERROR: main.go:162: {0 TimeoutExceeded 3.4400055s 0s 220 300 true <nil>}

When exceeding 220 the script  freezes until the global timeout hits.

**Comment by hikhvar** [comment]
#17 introduces timeouts for publishing actions. This should prevent freezes due to blocking sends.

**Comment by choclaudio** [comment]
@arnoldbechtoldt I will try to get some time for this during the coming week. I think I still have the scenario stored somewhere.

**Comment by arnisoph** [comment]
Feel free to reopen this issue if it still exists.. :)
