### ISSUE TITLE
parameter for QoS & retain

### ISSUE THREAD

**Issue by choclaudio** [inovex/mqtt-stresser#14]
It would be of value to be able to set the QoS level for subscribers and publishers. The retain value for publishers is also valuable when stress testing different scenarios.

I  suggest:
-publisher-qos
-subscriber-qos
-retain

**Comment by flyisland** [comment]
+1

**Comment by arnisoph** [comment]
This has been implemented by @hikhvar and is now available (https://github.com/inovex/mqtt-stresser/releases/tag/v3). Big applause to @hikhvar!
