### ISSUE TITLE
What's the size of one message you send to the broker for the pressure test?

### ISSUE THREAD

**Issue by Hapoa** [inovex/mqtt-stresser#25]
```
  < 147 msg/sec  75%
  < 155 msg/sec  93%
  < 164 msg/sec  96%
  < 181 msg/sec  97%
  < 190 msg/sec  98%
  < 215 msg/sec  99%
  < 232 msg/sec  100%
```

msg/sec only, but what's the the length of each msg?

**Comment by hikhvar** [comment]
https://github.com/inovex/mqtt-stresser/blob/8d363b710bbcd32aba02bd0a343a3ed2d67d17d2/worker.go#L122

This is the line which generates the payload. It's at least 13 bytes. It will increase if you send more messages. Actually the stress test focus more on message throughput then payload throughput. However pull requests to test with predefined message sizes are welcome.

**Comment by Hapoa** [comment]
Thank you for response.
