### ISSUE TITLE
Can we add a 'wait' period between each message being sent?

### ISSUE THREAD

**Issue by Mac351** [inovex/mqtt-stresser#40]
I want to simulate a situation where we have many clients, sending a message once a minute. 

I'd suggest a new parameter that accepts a wait time in seconds, like wait-period and then in the worker, add a thread sleep (or similar) to wait for the required period of time.

Awesome tool by the way, thanks!

**Comment by hikhvar** [comment]
Instead of a wait period I think, a maximal rate per second feels more natural. In general I like this idea. Do you want to implement this feature? A PR is very welcome.

**Comment by Mac351** [comment]
I would like to try, but my initial attempts to build locally didn't work, due to not having a "make" installed. I'm not sure if I'm going to get the time to sort this out.

**Comment by Mac351** [comment]
I've created a PR. I tried to link it to this issue, but that didn't work!
