### ISSUE TITLE
`Not connected` during test

### ISSUE THREAD

**Issue by cassc** [inovex/mqtt-stresser#43]
I was testing my mosquitto broker with the following command

```
mqtt-stresser -broker tcp://192.168.1.221:1883 \
   -num-clients 10000 \
   -num-messages 10 \
   -rampup-delay 200ms \
   -rampup-size 1000 \
   -global-timeout 180s \
   -timeout 20s
```

However the test stopped in the middle with the `Not Connected` error. Does this simply mean my broker can not handle 10K concurrent connections? 

```
1000 worker started - waiting 200ms
2000 worker started - waiting 200ms
3000 worker started - waiting 200ms
4000 worker started - waiting 200ms
5000 worker started - waiting 200ms
6000 worker started - waiting 200ms
7000 worker started - waiting 200ms
8000 worker started - waiting 200ms
9000 worker started - waiting 200ms
10000 worker started
.........................(many-dots-omitted-here)...........................Not Connected
```

**Comment by hikhvar** [comment]
I think this is undesired behavior. I labeled this a bug. I will have a look into the details.

**Comment by Jeyanthinath** [comment]
I am also facing the same issue, can you please explain when this error happens ?

**Comment by hikhvar** [comment]
I think I found the bug, can you please check if #45 fixes this for you?

**Comment by Jeyanthinath** [comment]
@hikhvar I didn't face the issue after the fix , thanks 👍🏽
