### ISSUE TITLE
Stress-testing test.mosquitto.org

### ISSUE THREAD

**Issue by Biswajeeban** [inovex/mqtt-stresser#5]
Every-time I try to stress-test  test.mosquitto.org, I am getting the following output/error(but works fine with other publicly hosted brokers). Please help me understand this and guide how can I get the full result.
thanks in advance.

 ./mqtt-stresser -broker tcp://test.mosquitto.org:1883 -nm-clients 100 -num-messages 10 -rampup-delay 1s -rampup-size 10 -global-timeout 180s -timeout 20s
10 worker started - waiting 1s
20 worker started - waiting 1s
30 worker started - waiting 1s
40 worker started - waiting 1s
50 worker started - waiting 1s
60 worker started - waiting 1s
70 worker started - waiting 1s
80 worker started - waiting 1s
90 worker started - waiting 1s
100 worker started
EEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEpanic: close of nil channel

goroutine 23 [running]:
panic(0x6f54c0, 0xc820336670)
	/usr/lib/go-1.6/src/runtime/panic.go:481 +0x3e6
github.com/eclipse/paho%2emqtt%2egolang.(*client).closeStop(0xc82015af00)
	/home/install/go/src/github.com/eclipse/paho.mqtt.golang/client.go:482 +0x1b2
github.com/eclipse/paho%2emqtt%2egolang.(*client).disconnect(0xc82015af00)
	/home/install/go/src/github.com/eclipse/paho.mqtt.golang/client.go:495 +0x2b
github.com/eclipse/paho%2emqtt%2egolang.(*client).Disconnect(0xc82015af00, 0x5)
	/home/install/go/src/github.com/eclipse/paho.mqtt.golang/client.go:439 +0x314
main.(*Worker).Run.func2(0xc820092500, 0x7fc524d3d910, 0xc82015af00, 0xc820012900, 0x3f)
	/home/install/Downloads/Brokers/benchmark/mqtt-stresser-master/worker.go:70 +0x304
main.(*Worker).Run(0xc820092500)
	/home/install/Downloads/Brokers/benchmark/mqtt-stresser-master/worker.go:163 +0x23fe
created by main.main
	/home/install/Downloads/Brokers/benchmark/mqtt-stresser-master/main.go:137 +0x96a

**Comment by invadersmustdie** [comment]
Looks like test.mosquitto.org has a cap on number of active connections. When running with a lower number of client (`-num-clients 3`) it's working.
