### ISSUE TITLE
Error running sample EMQX Engine

### ISSUE THREAD

**Issue by rupennugitech** [inovex/mqtt-stresser#50]
I am facing error running sample emqx free server

Below is the command 
       docker run inovex/mqtt-stresser -broker  mqtt://broker.emqx.io:1883     -num-clients 100 -num-messages 10 -rampup-delay 1s -rampup-size 10 -global-timeout 180s -timeout 20s -skip-tls-verification true

Error i am getting is 
Efailed to unsubscribe: Not Connected
Efailed to unsubscribe: Not Connected

**Comment by arnisoph** [comment]
Please change mqtt:// to tcp://.

```
$ docker run --rm inovex/mqtt-stresser -broker tcp://broker.emqx.io:1883 -num-clients 1 -num-messages 10 -rampup-delay 1s -rampup-size 10 -global-timeout 180s -timeout 20s
1 worker started
.
# Configuration
Concurrent Clients: 1
Messages / Client:  10

# Results
Published Messages: 10 (100%)
Received Messages:  10 (100%)
Completed:          1 (100%)
Errors:             0 (0%)

# Publishing Throughput
Fastest: 2832 msg/sec
Slowest: 2832 msg/sec
Median: 2832 msg/sec

  < 2832 msg/sec  100%

# Receiving Througput
Fastest: 49 msg/sec
Slowest: 49 msg/sec
Median: 49 msg/sec

  < 49 msg/sec  100%
```


@hikhvar I am not aware of mqtt://, maybe we should dig into latest MQTT development and also verify MQTT5 support.

**Comment by hikhvar** [comment]
I think we do not support MQTT5 at the moment. The MQTT client needs an update.

**Comment by arnisoph** [comment]
Closing due to lack of feedback.
