### ISSUE TITLE
How to use stresser with mqtt authentication (user name and password)

### ISSUE THREAD

**Issue by carlosjpr-collab** [inovex/mqtt-stresser#67]
How to start the stesser with user name and password  for mqtt authentication?

**Comment by arnisoph** [comment]
try

```
-username <user> -password <pass>
```

https://github.com/inovex/mqtt-stresser/blob/master/main.go#L39

**Comment by hikhvar** [comment]
@carlosjpr-collab as you use those flags in #68, I think this is resolved. Will close this.
